### ISSUE TITLE
Modal windows are not destroyed on close

### ISSUE THREAD

**Issue by Tuttu** [kylefox/jquery-modal#124]
Hey there !

I'm using this plugin for quite some time now and I figured that my modal content is never removed from the DOM when I close a modal window, whatever the method (Close button, Escape or click on the layout).
Instead, the `<div>` gets a `display: none;` CSS property and I can't figure why. Is that a setting or I'm facing some kind of bug ?
It was no big deal until now but it started to create problems as soon as I were using it to create forms and fetching data from them with Javascript. Javascript was always looking at the data of the first created form so that's how I figured they were never destroyed, just hidden.

I don't know if that matters but I'm creating my modal window like that : 

    $.ajax({
	url : 'Functions.php',
	type : 'POST',
	data : 'Action=myQuery&ID=' + myID, 
	dataType : 'html',
	success : function(result, statut){
	    $(result).modal();
	},
	});	

If this is more a bug than a setting that I'm not aware of, I will try to write a small fiddle to reproduce this problem.

**Comment by kylefox** [comment]
That's the intended behaviour — the library doesn't assume you want the element removed from the DOM upon close. For example, you might have a modal login form HTML fragment sitting (hidden) in the DOM. If the user opens and then closes it, you don't want the login form removed from the DOM — if you did, the user couldn't open it again because it's no longer in the DOM.

Modals opened with the built-in (simple) AJAX functionality (ex: `<a href="cart.php" rel="modal:open">View Cart</a>`) _will_ be automatically removed from the DOM when closed.

Because you're creating the AJAX modal manually, you'll also need to remove it manually. You can do this by binding to the `$.modal.CLOSE` event. Something like this inside your success handler:

```javascript
modal.on($.modal.CLOSE, function(event, m) { m.elm.remove(); };);
```

_(I'm going from memory and haven't tested that code, so you might need to fiddle with it a bit :) But that's the general idea.)_

**Comment by Tuttu** [comment]
Oh, that makes sense now. I started to use your plugin back in January and I had to put my project in stand by until recently so I might have forgot this behavior. 
Thanks for the explanation and the answer lead. I will try it tomorrow. :)

**Comment by kylefox** [comment]
:+1:

**Comment by Tuttu** [comment]
Just a small note to confirm that your line of code work. I just had to use it like that and it was alright. It looks like you have a pretty solid memory. ;) 

        $("body").on($.modal.CLOSE, function(event, m) {
		m.elm.remove(); 
	});

**Comment by c4dw** [comment]
close function add ;
      this.remove();


close: function() {
      modals.pop();
      this.unblock();
      this.hide();
      this.remove();
      if (!$.modal.isActive())
        $(document).off('keydown.modal');
},

**Comment by vrnvorona** [comment]
I am late here, but that issue saved me a lot of time, thanks a lot guys
