### ISSUE TITLE
Change "rel" to "data-toggle"

### ISSUE THREAD

**Issue by greg-raven** [kylefox/jquery-modal#140]
I recommend changing the “rel” attribute to “data-toggle” so the resulting HTML code will validate. I've never been able to figure out GitHub, so here is the altered code on Dropbox:

https://www.dropbox.com/sh/5es4y1zv2mxkw72/AABA7kZUnYZhrZBG2VU9npqva?dl=0

I did not change the min.js version of the code.

**Comment by hultberg** [comment]
You just branch out of master, make your changes and then push back in a fork you have created on GitHub. Then GitHub makes your life so easy by asking if you want to make a Pull Request.

Is there any other benefit of using a data attribute? `rel` – according to mdn – is used for anchors, not excating a modal is it?

**Comment by kylefox** [comment]
I actually didn't realize people still validated their HTML :sweat_smile: 

I'm not opposed to moving to `data-*` attributes instead of `rel`, but I'm also not certain it's worth changing. There are probably some nuances to discuss in how it would function. Would it be a straight across replacement? For example:

```html
<a href="login.html" data-toggle="modal:open">Login</a>
```

**Comment by greg-raven** [comment]
As far as I know, yes. It works for me, both in terms of validating and in terms of the code working as expected.
