### ISSUE TITLE
Create programmatically?

### ISSUE THREAD

**Issue by mscreenie** [kylefox/jquery-modal#160]
I want to create / open a modal programmatically and write html inside the modal afterwards. I don't have any pre-defined html.

Any ideas? I've searched the docs for programmatically terms but nothing.?

**Comment by kylefox** [comment]
See [Opening Manually](https://github.com/kylefox/jquery-modal#method-2-manually) and [Events](https://github.com/kylefox/jquery-modal#events).

Just call `.modal()` on your element. You can use normal jQuery to modify the content of the element. You can bind to the modal events, such as `'modal:before-open'` in order to change the HTML of the modal before it's shown.

This code is untested, but it should be enough to give you the idea and get started:

```html
<form id="login-form" class="modal">
  <!-- your HTML -->
</form>
```

```javascript
$('#login-form').on($.modal.BEFORE_OPEN, function(event, modal) {
  // Modify your HTML here.
  $('#login-form').append("<p>Hello!</p>");
});

$('#login-form').modal();
```
