### ISSUE TITLE
double click

### ISSUE THREAD

**Issue by LeniM** [kylefox/jquery-modal#168]
Hi,

Just wanted let you know that when you double click on a link you get this error message 
```
Uncaught TypeError: Cannot read property 'children' of null
```
and the loader stays on

http://codepen.io/lenim/pen/oLVykR

**Comment by kylefox** [comment]
Good catch, but I don't think this is worth handling in the library itself. Feel free to open a pull request (see [Contributing](https://github.com/kylefox/jquery-modal#contributing)) if you have an idea for how to cleanly implement this. Thanks!

**Comment by KOEI5113** [comment]
Just facing the same issue. 
I guess mainly because of the previous ajax already set `$.modal.$blocker` as null.
So when next ajax, which be trigged in short time, trying to get `$.modal.$blocker`'s children will get an error.

After I edit the source code like below, everything seems to go well.
```javascript
unblock: function(now) {
  if (!now && this.options.doFade)
    this.$blocker.fadeOut(this.options.fadeDuration, this.unblock.bind(this,true));
  else {
  	if(this.$blocker !== null){
  		this.$blocker.children().appendTo(this.$body);
        this.$blocker.remove();
        this.$blocker = null;	
  	}
    
    selectCurrent();
    if (!$.modal.isActive())
      this.$body.css('overflow','');
  }
},
````
Maybe this worth for a PR but I'm not sure. 
After all, I not really good at javascript and just use this lib for a couple of days.
