### ISSUE TITLE
Small screen will make the modal go down

### ISSUE THREAD

**Issue by virtapoika** [kylefox/jquery-modal#174]
Using a small screen appears to make weird popping of the modal to a lot lower so that you need to  scroll... Interesting...

**Comment by GiancarloJSantos** [comment]
Yep. It happens in my app also. Any sugestions? Is there a workaround?

**Comment by kylefox** [comment]
I wonder if it's related to the `max-width: 400px;` [default CSS](https://github.com/kylefox/jquery-modal/blob/master/jquery.modal.css#L28). It appears to be "popping" when the viewport is narrow than this width.

Is that approximately what you're noticing @virtapoika & @GiancarloJSantos ?

Maybe try experimenting with the `width` style, and even try changing it to a `max-width` instead. TBH the hard-coded width is kind of a pain, and something I'd like to get ride of in [jQuery Modal 2.0](https://github.com/kylefox/jquery-modal/issues/169)

**Comment by montyvesselinov** [comment]
replacing width: 400px with width: 90% in default CSS fixes the problem; very annoying

**Comment by kylefox** [comment]
Ok, I've fixed this in [v0.8.0](https://github.com/kylefox/jquery-modal/tree/v0.8.0). You can try the examples at [jquerymodal.com](http://jquerymodal.com/).

In summary, the default styles for `.modal` have been changed:

* Use `width: 90%;` rather than a hard-coded pixel value
* Use `max-width: 500px;` to prevent extremely wide content (can easily be overridden or removed with `max-width: none;`
* Use `box-sizing: border-box;` so that calculated width is never larger than the viewport (which caused the modal to "pop" to the bottom of the page at narrow screen sizes).
