### ISSUE TITLE
Cannot get select2 dropdown working correctly in modal

### ISSUE THREAD

**Issue by cyphix333** [kylefox/jquery-modal#187]
Hello,

I am trying to get the jQuery plugin select2 working correctly within a modal, however because I have the modal set to `display: none` to start with I need to reinitialize select2.

Let me note that it works fine if I _don't_ hide the modal by default, but obviously you need to.

So I tried this code:

```
$('.modal').on('modal:open', function(e){

    $(e.target).find('select').select2('destroy').select2();

});
```

However it didn't seem to work; I can destroy it fine, so it's getting the instance, but it's failing to resize itself properly, which tells me the select is still hidden when it attempts to reinitialize - but this sppears to be the most relevant event for what I need to do?

**Comment by kylefox** [comment]
Hi, sorry about the delay. It looks like you're on the right track, and hopefully you found a solution — if so, feel free to share 😄 

Unfortunately I won't be able to help troubleshoot further without a publicly-accessible test case that demonstrates the problem. If you're able to link to one, I can re-open and investigate.

**Comment by cyphix333** [comment]
Sure, here you go: http://codepen.io/anon/pen/NbdEag :)

**Comment by kylefox** [comment]
The problem is that when you initially resize your `<select>` elements on page load, the _hidden select elements don't have a reliable width._ From the jQuery docs for [`.width()`](http://api.jquery.com/width/#width1):

> The value reported by `.width()` is not guaranteed to be accurate when the element or its parent is hidden. To get an accurate value, ensure the element is visible before using `.width()`. 

You can verify this by logging the width during page load:

```javascript
$('select').each(function(i, obj) {

  // Format our new width
  var sel_width = $(this).width() + 30 + 'px';

  console.log(sel_width);  // <== Probably not what you expect for hidden selects! 😬

  $(this).css('width', sel_width);  // <== Now your CSS width is wrong.
});
```

The solution is to

1. Destroy the `select2` when the modal is opened
2. _Remove_ any widths that were applied to the `<select>` at page load: `.css('width', 'auto');`
3. Resize your `<select>`
4. Reinitialize `select2`

You could combine step 2 & into a single function and call it at page load _and_ when your modal opens.

```javascript
function resizeSelects() {
  $('select').each(function(i, obj) {

      // Reset any existing widths.
      $(this).css('width', 'auto');  // <== 🎉 NEW 🎉

      // Format our new width
      var sel_width = $(this).width() + 30 + 'px';

      // Apply width
      $(this).css('width', sel_width);

  });
}

// Immedaitely call on page load.
resizeSelects();
```

Then your modal handler needs to call `resizeSelects()` _after_ destroying and _before_ reinitializing select2.

```javascript
$('.modal').on('modal:open', function(e){
  // Convert back to <select>
  $(e.target).find('select').select2('destroy');

  // Reset/reset
  resizeSelects();  // <== 🎉 NEW 🎉

  // Initialize select2
  $(e.target).find('select').select2({minimumResultsForSearch: Infinity});
});
```


You can see it all working here: http://codepen.io/kylefox/pen/vygoXx

**Comment by kylefox** [comment]
Also, I see you're using Bootstrap — you might run into issues because Bootstrap has it's own class/styles for `.modal`. For example, it's why the Close X button in the top-right corner is getting cut off:

![image](https://cloud.githubusercontent.com/assets/37838/20465854/97f3a7fc-af24-11e6-9324-56ed0ebe21a5.png)

Adding this to your CSS will fix that problem, but you may run into other issues.

```css
.modal {
  overflow: visible;
}
```

**Comment by cyphix333** [comment]
Hey thanks for checking that out and finding out the issue, I will let you know how it goes.

As for the Bootstrap issue, yeah, the one I put on codepen was just a quick throw together and only partially looks like the one I am using - the "x" button issue is all good, but thanks for the heads up anyway :)

**Comment by cyphix333** [comment]
Ok, tested it out and it worked a charm - thanks again for finding the issue :)

I did some small tweaks just so it doesn't cycle through all the selects on the page every time a modal is opened...

**Page load:**

```
resizeSelects($('select'));
```

**On modal open:**

```
$('.modal').on('modal:open', function(e){

    // Get our select elements
    var selects = $(e.target).find('select');

    // Destroy any select2 instances on them
    selects.select2('destroy');

    // Now do our resizing fixes...
    resizeSelects(selects);

    // Reinitialise select2
    selects.select2({minimumResultsForSearch: Infinity});

});
```

**Resize function:**

```
function resizeSelects(selects) {

    selects.each(function(i, obj){

        // Reset any existing widths
        $(this).css('width', 'auto');

        // Format our new width
        var sel_width = ($(this).width() + 30) + 'px';

        // Apply width
        $(this).css('width', sel_width);

    });

}
```

I probably should store the `select2` options in a variable or something though.

**Comment by kylefox** [comment]
No problem :) Yeah there are a number of ways the code could be improved / optimized in general. Moving your `select2` options to a variable. Another suggestion could be to limit your resizing to only those selects which are currently visible using the [`:visible` selector](http://api.jquery.com/visible-selector/):

```javascript
function resizeSelects(selects) {

    selects.filter(':visible').each(function(i, obj){

        // Reset any existing widths
        $(this).css('width', 'auto');

        // Format our new width
        var sel_width = ($(this).width() + 30) + 'px';

        // Apply width
        $(this).css('width', sel_width);

    });

}
```

**Comment by cyphix333** [comment]
Ahh yes, good idea :)
