### ISSUE TITLE
Pressing Enter key on a modal with "fadeDuration" set

### ISSUE THREAD

**Issue by szgeri** [kylefox/jquery-modal#198]
If you press ENTER on a modal that has "fadeDuration" set, the modal goes away but the semi-transparent background fader stays visible.

Example 7 at jquerymodal.com shows the problem. Reproduced in Chrome and Firefox.

Workaround: do not set a fadeDuration.

**Comment by joelbitar1986** [comment]
Thanks for saving me potentially hours trying to diagnose the same issue I was having.

**Comment by kylefox** [comment]
It _looks_ like the root cause of this issue is that after clicking a link that opens a modal, hitting `enter` effectively "clicks" that link again, causing the modal to re-open.

It only _appears_ to be related to the `fadeDuration` option because the animation & delay make it obvious. Without animation or delay, the modal re-opens _instantly_ and therefore the problem is not visible.

Some potential solutions:

1. Modify the automatic event handlers so that when a link is clicked and it's modal opened, it can't be re-opened (i.e. don't open that link's modal if it's already open).
2. I think ideally _all_ interactions with the underlying page should be prevented. We already do this with mouse events (via the overlay), but we don't with keyboard interactions (the source of this bug).

I'm not sure that (2) is possible, and even if it is it sounds like a potential accessibility issue. So maybe (1) is the best approach?
