### ISSUE TITLE
using display:flex  

### ISSUE THREAD

**Issue by dkebler** [kylefox/jquery-modal#200]
Your code injects display:block on modal:open  but I'm doing a 100% flexbox site and my own css so I need display:flex.

Do you (can you) have an option for this.  Is there a work around.  Otherwise I'll have to fork your code :-(.

```html
<div id="modal-bookmark" class="section--modal modal" style="display: block;">
```

**Comment by dkebler** [comment]
Looks like nobody home to help.   By not loading your css and just copying and editing the blocker and modal classes I can work around this.

**Comment by kylefox** [comment]
Hey, thanks for pointing this out. It's a good point. For V2 I'd _really_ like to move more of this to CSS. So, rather than the scripts adding `display: block;` to the modal element, we simply add a class, ex: `.addClass('open');` — and the styles for displaying that are defined in the CSS. It would make it much easier to override & customize, like you needed to in this scenario.
