### ISSUE TITLE
Customization CSS modal.

### ISSUE THREAD

**Issue by quintendewilde** [kylefox/jquery-modal#247]
NOT REALLY AN ISSUE! FEATURE REQUEST MORE.

I'm not able to find how you style the modal itself thru css? 

And the Jquery modal site doesn't really show any example except for the example itself but not how it is made. 

I looked into the source code and can't find anything there either. 
Maybe a small tutorial would be interesting for new user.

kind regards

**Comment by kylefox** [comment]
The best way to understand how to style the modal is to look at the source code for the default styles, which are in [`jquery.modal.css`](https://github.com/kylefox/jquery-modal/blob/master/jquery.modal.css).

For example, to make the overlay background semi-transparent white instead of dark grey, you could do something like this:

```css
/* jquery.modal.custom.css */
.blocker {
  background-color: rgba(255, 255, 255, 0.75);
}
```

Just be sure to include your custom CSS file _after_ including the defaults:

```html
<!-- jQuery Modal script/style defaults -->
<script src="/js/jquery.modal.min.js"></script>
<link rel="stylesheet" href="/css/jquery.modal.min.css" />

<!-- Your customizations -->
<link rel="stylesheet" href="/css/jquery.modal.custom.css" />
```

You may need to use the [Chrome DevTools](https://developers.google.com/web/tools/chrome-devtools/css/) to inspect the HTML in order to understand what the different elements are.
