### ISSUE TITLE
Any way to change URL when modal is open?

### ISSUE THREAD

**Issue by SixFingeredAmish** [kylefox/jquery-modal#250]
Hi,

How would I get the url to change when a modal is open?

Thank you

**Comment by kylefox** [comment]
You might be able to use the browser's [`window.history.pushState` API](https://developer.mozilla.org/en-US/docs/Web/API/History_API#Adding_and_modifying_history_entries) within an event handler, possibly the `'modal:before-block'` event. See the [Events](https://github.com/kylefox/jquery-modal#events) section in the README for a list of available events.

However, modifying the history is outside the scope of this plugin. If you need further assistance, the best place to ask is Stack Overflow,

**Comment by SixFingeredAmish** [comment]
Thanks! I was able to get this working using:
```
$('a[rel="modal:open"]').click(function(event) {
  var url = $(this).attr('href');
  history.pushState(null, null, url);
});
```
However, would you happen to know why the inverse of this for closing modal doesn't work?
$(a[rel="modal:close"]').click(function() {
  history.pushState(null, null, "/");
});

**Comment by kylefox** [comment]
Depending on how you're opening the modal, the close button element might not be present in the DOM at the time your event handler is bound. From [the jQuery docs for `$.on`](https://api.jquery.com/on/):

> Event handlers are bound only to the currently selected elements; they must exist at the time your code makes the call to .on().

So you might need to use _delegated event handlers_ as described in the docs, something like this:

```javascript
$(document).on('click', 'a[rel="modal:close"]', function() {
  history.pushState(null, null, "/");
});
```

This is purely a guess — no guarantees that it fixes your issue.

However, I'd recommend using the [`'modal:after-close'` event](https://github.com/kylefox/jquery-modal#events) rather than binding to the click event on the close button. This is because the modal can be closed in other ways (for example, hitting the `Esc` key or clicking the overlay), and if you're only listening to click events on the close button, your handlers will never run if the modal is closed by these other methods.

**Comment by SixFingeredAmish** [comment]
I used delegated event handlers you gave and it worked!

I have tried using the modal event in the past, but I keep running into this error
```
Cannot read property 'AFTER_CLOSE' of undefined
```

**Comment by kylefox** [comment]
Make sure you're attaching your event handers within a `$()`, for example:

```javascript

$(function() {
  $(document).on($.modal.AFTER_CLOSE, function() {
    history.pushState(null, null, "/");
  });
});
```

Or just use the literal string `'modal:after-close'` instead of `$.modal.AFTER_CLOSE`

**Comment by SixFingeredAmish** [comment]
Wow this fixed everything. Thank you

**Comment by arundhati1213** [comment]
@steakscience Can you please share the full code with me ?
HTML and JS part

**Comment by arundhati1213** [comment]
@steakscience I used this code for getting back to main url 
$(function () {
            $(document).on($.modal.after-close, function () {
                history.pushState(null, null, "/");
            });
        });

Ex - this is my mail url - http://127.0.0.1:5500/pop-up.html
after open the modal it comes  http://127.0.0.1:5500/pop-up.html#ex1 (Which is correct)
after close the url should be http://127.0.0.1:5500/pop-up.html instead of http://127.0.0.1:5500/

Can you please help me to do this?

**Comment by tarikcanmr** [comment]
Hello guys. I figured out how to catch this when the modal close. If there using modal with ajax or something you need to use after show modal code.

```

$('#modalid').on('hidden.bs.modal', function (event) {
     alert("closed");
});

```
