### ISSUE TITLE
Appends to the container, because it doesn't add class 'blocker'

### ISSUE THREAD

**Issue by stelasido** [kylefox/jquery-modal#251]
Hi, there is a problem with the plugin. There is no position like fixed/absolute and the modal just appends to the parent element and that's all. In your examples, I see that the script adds 'blocker' class which is with position fixed, but when I try this class isn't added.
I am using this code:
        $('.modal').modal();`

**Comment by stelasido** [comment]
Instead it is added `.modal-backdrop`, which is with position absolute, but position absolute cont is blocked in closest parent container with position relative.

**Comment by kylefox** [comment]
This plugin does not use a `.modal-backdrop` class, but the [Bootstrap Modal](https://getbootstrap.com/docs/4.3/components/modal/#usage) does. I suspect you might be trying to use both plugins on your page, which won't work because [this plugin is not compatible with Bootstrap](https://github.com/kylefox/jquery-modal#installation).

But if I'm wrong, and you aren't using Bootstrap, please provide a publicly-accessible page that demonstrates the bug. Thanks!
