### ISSUE TITLE
Modal's content is not visible

### ISSUE THREAD

**Issue by leocrespo** [kylefox/jquery-modal#86]
The dialog is in the same layer as the background. Changing the modal's z-index doesn't help. 

http://cl.ly/image/0h272V1G0k3u

**Comment by COLABORATI** [comment]
I had the same problem, but the solution does not apply. In my case the real problem is that the modal always has a z-index of 2 applied - I do not know where this happens. I did not find the string 'z-index' anywhere in the sources and the z-index is neither set in any css, so currently this is unresolved. I will open a more specific issue with a question about how to set the z-index for a modal.
